# Generated by Django 4.1.7 on 2023-02-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_user_bio_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppermissionrole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppermissionrole',
            name='group_permission',
        ),
        migrations.RemoveField(
            model_name='grouppermissionrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='grouppermissionuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppermissionuser',
            name='group_permission',
        ),
        migrations.RemoveField(
            model_name='grouppermissionuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouprole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouprole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_admins',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_members',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_owner',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_permissions',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_roles',
        ),
        migrations.DeleteModel(
            name='Adminship',
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
        migrations.DeleteModel(
            name='GroupPermissionRole',
        ),
        migrations.DeleteModel(
            name='GroupPermissionUser',
        ),
        migrations.DeleteModel(
            name='GroupRole',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
