# Generated by Django 4.1.7 on 2023-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
