# Generated by Django 4.1.7 on 2023-03-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_user_is_banned_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
    ]
